version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_app
    container_name: laravel_app
    volumes:
      - ./src:/var/www/html  # Map the src folder for the Laravel project
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root  # Set root as the username
      MYSQL_PASSWORD: root  # Set root password
      MYSQL_ROOT_PASSWORD: root  # Set root password for MySQL root access
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db  # Link to the MySQL database service
      MYSQL_ROOT_PASSWORD: root  # MySQL root password to login via phpMyAdmin
    ports:
      - '8080:80'  # Expose phpMyAdmin on port 8080
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - '8000:80'  # Map host port 8000 to container port 80 for Nginx
    volumes:
      - ./src:/var/www/html  # Map the src folder to Nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Load Nginx configuration
    depends_on:
      - app

volumes:
  db_data:
